workflows:
    react-native-android:
        name: React Native Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
            java: 17
            vars:
                PACKAGE_NAME: "com.example.codemagicsample"
        scripts:
        - name: Install npm dependencies
          script: |
            npm install
        - name: Set Android SDK location
          script: |
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Build Android release
          script: |
                cd android
                ./gradlew assembleRelease

        artifacts:
        - android/app/build/outputs/**/*.aab
